name = "TkIntcode"
uuid = "1ef6b8e2-9cad-4bde-a5b4-63cef2b5f2e1"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
